#!/usr/bin/env python3
"""asm.py — a tiny two-pass RV32I assembler for this project's test programs.

Not a full toolchain: it supports the RV32I base integer instructions plus a
handful of pseudo-ops, enough to write readable, reproducible CPU test
programs whose machine encodings are generated by code instead of hand-typed
hex (which is where bit-scramble bugs hide).

Usage:
    python scripts/asm.py sim/programs/foo.s -o sim/programs/foo.hex

Output is one 32-bit little-endian instruction word per line, 8 hex digits,
suitable for Verilog $readmemh into a word-addressed memory.

Syntax:
    # comment            ; comment          // comment
    label:
        addi x1, x0, 5
        lw   a0, 8(sp)
        beq  x1, x2, label
        j    label
    Registers: x0-x31 or ABI names (zero ra sp gp tp t0-t6 s0-s11 a0-a7 fp).
    Immediates: decimal, 0x-hex, or a label (for branches/jumps only).
Pseudo-ops: nop, mv rd,rs, li rd,imm(32-bit), j label, jr rs, ret,
            beqz/bnez rs,label, ecall, ebreak.
"""
import sys, re, argparse

ABI = {
    'zero':0,'ra':1,'sp':2,'gp':3,'tp':4,'t0':5,'t1':6,'t2':7,
    's0':8,'fp':8,'s1':9,'a0':10,'a1':11,'a2':12,'a3':13,'a4':14,'a5':15,
    'a6':16,'a7':17,'s2':18,'s3':19,'s4':20,'s5':21,'s6':22,'s7':23,
    's8':24,'s9':25,'s10':26,'s11':27,'t3':28,'t4':29,'t5':30,'t6':31,
}

def reg(tok):
    tok = tok.strip().lower()
    if tok in ABI: return ABI[tok]
    m = re.fullmatch(r'x(\d+)', tok)
    if m and 0 <= int(m.group(1)) <= 31: return int(m.group(1))
    raise ValueError(f"bad register: {tok!r}")

def imm(tok, symtab=None, pc=None, rel=False):
    tok = tok.strip()
    if symtab is not None and tok in symtab:
        return symtab[tok] - pc if rel else symtab[tok]
    return int(tok, 0)

def rtype(f7,f3,op): return lambda rd,rs1,rs2: (f7<<25)|(rs2<<20)|(rs1<<15)|(f3<<12)|(rd<<7)|op
def itype(f3,op):    return lambda rd,rs1,im: ((im&0xFFF)<<20)|(rs1<<15)|(f3<<12)|(rd<<7)|op
def shtype(f7,f3,op):return lambda rd,rs1,sh: ((f7)<<25)|((sh&0x1F)<<20)|(rs1<<15)|(f3<<12)|(rd<<7)|op

def enc_s(f3,op,rs2,rs1,im):
    im&=0xFFF
    return (((im>>5)&0x7F)<<25)|(rs2<<20)|(rs1<<15)|(f3<<12)|((im&0x1F)<<7)|op

def enc_b(f3,op,rs1,rs2,im):
    im&=0x1FFF
    b12=(im>>12)&1; b11=(im>>11)&1; b10_5=(im>>5)&0x3F; b4_1=(im>>1)&0xF
    return (b12<<31)|(b10_5<<25)|(rs2<<20)|(rs1<<15)|(f3<<12)|(b4_1<<8)|(b11<<7)|op

def enc_u(op,rd,im): return ((im&0xFFFFF)<<12)|(rd<<7)|op

def enc_j(op,rd,im):
    im&=0x1FFFFF
    b20=(im>>20)&1; b10_1=(im>>1)&0x3FF; b11=(im>>11)&1; b19_12=(im>>12)&0xFF
    return (b20<<31)|(b10_1<<21)|(b11<<20)|(b19_12<<12)|(rd<<7)|op

R = {  # name: (funct7, funct3)
    'add':(0x00,0x0),'sub':(0x20,0x0),'sll':(0x00,0x1),'slt':(0x00,0x2),
    'sltu':(0x00,0x3),'xor':(0x00,0x4),'srl':(0x00,0x5),'sra':(0x20,0x5),
    'or':(0x00,0x6),'and':(0x00,0x7),
}
I = {  # name: funct3 (opcode 0010011)
    'addi':0x0,'slti':0x2,'sltiu':0x3,'xori':0x4,'ori':0x6,'andi':0x7,
}
SH = {'slli':(0x00,0x1),'srli':(0x00,0x5),'srai':(0x20,0x5)}
L = {'lb':0x0,'lh':0x1,'lw':0x2,'lbu':0x4,'lhu':0x5}   # opcode 0000011
S = {'sb':0x0,'sh':0x1,'sw':0x2}                        # opcode 0100011
Bc= {'beq':0x0,'bne':0x1,'blt':0x4,'bge':0x5,'bltu':0x6,'bgeu':0x7}

OP_R=0x33; OP_I=0x13; OP_L=0x03; OP_S=0x23; OP_B=0x63
OP_JAL=0x6F; OP_JALR=0x67; OP_LUI=0x37; OP_AUIPC=0x17; OP_SYS=0x73

def li_words(rd, val):
    """Expand `li rd, val` to 1 or 2 machine words. No labels involved, so this
    is safe to call in pass 1 (for sizing) and pass 2 (for encoding)."""
    val &= 0xFFFFFFFF
    lo = val & 0xFFF
    hi = (((val >> 12) + 1) if (lo & 0x800) else (val >> 12)) & 0xFFFFF
    if hi == 0:
        return [itype(0x0, OP_I)(rd, 0, val & 0xFFF)]
    return [enc_u(OP_LUI, rd, hi), itype(0x0, OP_I)(rd, rd, lo)]

def insn_words(m, args):
    """Number of machine words a source line emits (needed for pass-1 sizing).
    Only `li` is variable-length; everything else is exactly one word."""
    if m == 'li':
        a = split_ops(args)
        return len(li_words(reg(a[0]), imm(a[1])))
    return 1

def split_ops(s):
    return [t for t in re.split(r'[,\s]+', s.strip()) if t != '']

def parse_mem(operand):
    # "off(reg)" -> (imm_str, reg)
    m = re.fullmatch(r'\s*(-?[\w0x]+)\(\s*(\w+)\s*\)\s*', operand)
    if not m: raise ValueError(f"bad mem operand: {operand!r}")
    return m.group(1), m.group(2)

def assemble(lines):
    # ---- pass 1: addresses & labels ----
    prog = []   # (pc, mnemonic, args_str)
    symtab = {}
    pc = 0
    for raw in lines:
        line = re.split(r'[#;]|//', raw, maxsplit=1)[0].strip()
        if not line: continue
        while ':' in line:
            lbl, _, rest = line.partition(':')
            symtab[lbl.strip()] = pc
            line = rest.strip()
            if not line: break
        if not line: continue
        mnem, _, args = line.partition(' ')
        mnem = mnem.strip().lower(); args = args.strip()
        prog.append((pc, mnem, args))
        pc += 4 * insn_words(mnem, args)   # size-aware: `li` may be 2 words
    # ---- pass 2: encode ----
    words = []
    for pc, m, args in prog:
        words.extend(encode(pc, m, args, symtab))
    return words

def encode(pc, m, args, symtab):
    a = split_ops(args) if args else []
    def rel(label): return imm(label, symtab, pc, rel=True)
    # pseudo-ops
    if m == 'nop':   return [itype(0x0,OP_I)(0,0,0)]
    if m == 'mv':    return [itype(0x0,OP_I)(reg(a[0]),reg(a[1]),0)]
    if m == 'j':     return [enc_j(OP_JAL,0,rel(a[0]))]
    if m == 'jr':    return [itype(0x0,OP_JALR)(0,reg(a[0]),0)]
    if m == 'ret':   return [itype(0x0,OP_JALR)(0,1,0)]
    if m == 'beqz':  return [enc_b(0x0,OP_B,reg(a[0]),0,rel(a[1]))]
    if m == 'bnez':  return [enc_b(0x1,OP_B,reg(a[0]),0,rel(a[1]))]
    if m == 'li':
        return li_words(reg(a[0]), imm(a[1]))
    # real instructions
    if m in R:  f7,f3=R[m];  return [rtype(f7,f3,OP_R)(reg(a[0]),reg(a[1]),reg(a[2]))]
    if m in I:               return [itype(I[m],OP_I)(reg(a[0]),reg(a[1]),imm(a[2]))]
    if m in SH: f7,f3=SH[m]; return [shtype(f7,f3,OP_I)(reg(a[0]),reg(a[1]),imm(a[2]))]
    if m in L:
        off,rs1 = parse_mem(a[1]);  return [itype(L[m],OP_L)(reg(a[0]),reg(rs1),imm(off))]
    if m in S:
        off,rs1 = parse_mem(a[1]);  return [enc_s(S[m],OP_S,reg(a[0]),reg(rs1),imm(off))]
    if m in Bc:                     return [enc_b(Bc[m],OP_B,reg(a[0]),reg(a[1]),rel(a[2]))]
    if m == 'lui':                  return [enc_u(OP_LUI,reg(a[0]),imm(a[1]))]
    if m == 'auipc':                return [enc_u(OP_AUIPC,reg(a[0]),imm(a[1]))]
    if m == 'jal':
        if len(a)==1: return [enc_j(OP_JAL,1,rel(a[0]))]      # jal label -> ra
        return [enc_j(OP_JAL,reg(a[0]),rel(a[1]))]
    if m == 'jalr':
        off,rs1 = parse_mem(a[1]);  return [itype(0x0,OP_JALR)(reg(a[0]),reg(rs1),imm(off))]
    if m == 'ecall':                return [0x00000073]
    if m == 'ebreak':               return [0x00100073]
    raise ValueError(f"unknown mnemonic {m!r} (pc={pc})")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('src')
    ap.add_argument('-o','--out', required=True)
    args = ap.parse_args()
    with open(args.src) as f:
        words = assemble(f.readlines())
    with open(args.out,'w') as f:
        for w in words:
            f.write(f"{w & 0xFFFFFFFF:08x}\n")
    print(f"assembled {len(words)} words -> {args.out}")

if __name__ == '__main__':
    main()
