#!/usr/bin/env python3
"""Render a VCD dump to a publication-quality vector figure (SVG/PDF),
instead of screenshotting Vivado's waveform viewer.

Rationale: Vivado's GUI waveform viewer is dark-mode, low-contrast in print,
and a screenshot isn't reproducible (can't regenerate at higher res, can't
diff against a later run, can't be regenerated by a reviewer from your repo).
Rendering straight from the .vcd with matplotlib gives you a vector figure
that matches your paper's font/theme and is regenerated by re-running this
script -- keep the .vcd in the repo (or its path in bugs.jsonl /
detection_artifact) and this script turns it into Figure N on demand.

Requires: pip install vcdvcd matplotlib

Usage:
  render_waveform.py sim/waves/bug01.vcd --signals clk rst pc[31:0] stall \\
      --start 0 --end 2000 --out figures/bug01_load_use_hazard.svg
"""
import argparse
import sys

try:
    from vcdvcd import VCDVCD
except ImportError:
    sys.exit("pip install vcdvcd")
import matplotlib.pyplot as plt


def bits_to_steps(tv, tmax):
    times, vals = [], []
    for t, v in tv:
        times.append(t)
        vals.append(v)
    times.append(tmax)
    return times, vals


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("vcd")
    ap.add_argument("--signals", nargs="+", required=True, help="signal names as they appear in the vcd (see --list)")
    ap.add_argument("--list", action="store_true", help="list available signals and exit")
    ap.add_argument("--start", type=int, default=0)
    ap.add_argument("--end", type=int)
    ap.add_argument("--out", required=False)
    ap.add_argument("--title")
    a = ap.parse_args()

    v = VCDVCD(a.vcd)

    if a.list:
        for name in v.references_to_ids:
            print(name)
        return

    end = a.end or v.endtime
    fig, axes = plt.subplots(len(a.signals), 1, figsize=(9, 0.9 * len(a.signals)), sharex=True)
    if len(a.signals) == 1:
        axes = [axes]

    for ax, sig in zip(axes, a.signals):
        matches = [n for n in v.references_to_ids if n.endswith(sig) or n == sig]
        if not matches:
            sys.exit(f"signal not found: {sig} (use --list to see names)")
        data = v[matches[0]]
        tv = data.tv
        is_bus = any(x[1] not in ("0", "1", "x", "z") for x in tv)

        if is_bus:
            for i, (t, val) in enumerate(tv):
                t_next = tv[i + 1][0] if i + 1 < len(tv) else end
                if t_next < a.start or t > end:
                    continue
                ax.text((max(t, a.start) + min(t_next, end)) / 2, 0.5, val,
                         ha="center", va="center", fontsize=8, family="monospace")
                ax.axvline(max(t, a.start), color="black", linewidth=0.5)
            ax.set_ylim(0, 1)
            ax.set_yticks([])
        else:
            times, vals = bits_to_steps(tv, end)
            numeric = [1 if x == "1" else 0 for x in vals[:-1]] + [vals[-1] if isinstance(vals[-1], int) else 0]
            ax.step([t for t in times[:-1]] + [end], [1 if x == "1" else 0 for x in vals], where="post", linewidth=1.2)
            ax.set_ylim(-0.2, 1.2)
            ax.set_yticks([])

        ax.set_ylabel(sig, rotation=0, ha="right", va="center", fontsize=9)
        ax.set_xlim(a.start, end)
        for spine in ("top", "right", "left"):
            ax.spines[spine].set_visible(False)

    axes[-1].set_xlabel("time (ns)")
    if a.title:
        fig.suptitle(a.title)
    fig.tight_layout()

    if a.out:
        fig.savefig(a.out, bbox_inches="tight")
        print(f"wrote {a.out}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
